/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__cycapture__libtins___tins
#define __PYX_HAVE__cycapture__libtins___tins

struct PyPDUObject;
struct PyTCPStreamObject;

/* "cycapture/libtins/pdu_pxd.pxi":103
 * 
 * 
 * cdef public class PDU(object)[type PyPDUType, object PyPDUObject]:             # <<<<<<<<<<<<<<
 *     cdef cppPDU* base_ptr
 *     cdef object parent
 */
struct PyPDUObject {
  PyObject_HEAD
  struct __pyx_vtabstruct_9cycapture_7libtins_5_tins_PDU *__pyx_vtab;
  Tins::PDU *base_ptr;
  PyObject *parent;
};

/* "cycapture/libtins/tcp_stream_pxd.pxi":27
 * 
 * 
 * cdef public class TCPStream(object)[type PyTCPStreamType, object PyTCPStreamObject]:             # <<<<<<<<<<<<<<
 *     cdef readonly IPv4Address client_addr
 *     cdef readonly IPv4Address server_addr
 */
struct PyTCPStreamObject {
  PyObject_HEAD
  struct __pyx_obj_9cycapture_7libtins_5_tins_IPv4Address *client_addr;
  struct __pyx_obj_9cycapture_7libtins_5_tins_IPv4Address *server_addr;
  int client_port;
  int server_port;
  uint64_t identifier;
  int finished;
  PyObject *client_payload;
  PyObject *server_payload;
};

#ifndef __PYX_HAVE_API__cycapture__libtins___tins

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyPDUType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyTCPStreamType;

#endif /* !__PYX_HAVE_API__cycapture__libtins___tins */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_tins(void);
#else
PyMODINIT_FUNC PyInit__tins(void);
#endif

#endif /* !__PYX_HAVE__cycapture__libtins___tins */
